(define (sum-of-squares x y)
  (+ (* x x) (* y y)))

(define (sum-lrg x y z)
  (cond ((and (> x y) (> y z)) (sum-of-squares x y))
        ((and (> y x) (> z x)) (sum-of-squares y z))
        ((and (> z y) (> x y)) (sum-of-squares z x))))
(sum-lrg 3 2 1)
(sum-lrg 5 8 9)
(sum-lrg 5 1 2)   
